### ISSUE TITLE
Rename vscode-test to @vscode/test-electron

### ISSUE THREAD

**Issue by BrenekH** [BrenekH/kotlin-for-frc#126]
It appears that the `vscode-test` package has been renamed according to the following npm deprecation output: `npm WARN deprecated vscode-test@1.6.1: This package has been renamed to @vscode/test-electron, please update to the new name`

This should just be a simple name change in the `package.json`.

**Comment by anuragh2002** [comment]
Hey @BrenekH I would like to work on this issue. Can you please assign it to me?
