### ISSUE TITLE
Simulator not working on brand new project

### ISSUE THREAD

**Issue by narmstro2020** [BrenekH/kotlin-for-frc#145]
Hello.  I created and then converted a brand new empty project to Kotlin and attempted to run the simulator and got this as a result 

FAILURE: Build failed with an exception.

* What went wrong:
Project '.gradle.java.home=C' not found in root project 'StartingPointTemplate'.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

**Comment by narmstro2020** [comment]
Where do I go to set these

**Comment by BrenekH** [comment]
Just in the normal [VSCode settings page](https://code.visualstudio.com/docs/getstarted/settings)

**Comment by narmstro2020** [comment]
Is it the Kotlin For FRC > Simulate: Java Home.  

If so it is blank

**Comment by BrenekH** [comment]
What about the `java.home` setting?

**Comment by narmstro2020** [comment]
There isn't a java.home setting.  

There is 
Java > Import > Gradle: Home
Java > Import > Gradle > Java:Home
Java > Jdt > Ls > Java: Home

**Comment by BrenekH** [comment]
There is a `java.home`, but it looks like it got deprecated in favor of `java.jdt.ls.java.home`. I'm going to have to think about if I want to follow or if I want to just not use it.

In the meantime, just set `kotlinForFRC.simulate.javaHome` to the location of the WPILib JRE and everything __should__ work. (Be sure to use a forward slash `/` or a double backslash `\\` as the path separator)

**Comment by narmstro2020** [comment]
no dice.  Set the variable to the the C:\\Users\\Public\\wpilib\\2023\\jdk\\

no simulator

**Comment by narmstro2020** [comment]
Command that is failing

.\gradlew.bat simulateJava -Dorg.gradle.java.home="C:\\Users\\Public\\wpilib\\2023\\jdk\\"

**Comment by narmstro2020** [comment]
With what went wrong
* What went wrong:
Project '.gradle.java.home=C' not found in root project 'test5'.

**Comment by BrenekH** [comment]
Are you sure you used double backslashes like so: `C:\\Users\\Public\\wpilib\\2023\\jdk`?

**Comment by narmstro2020** [comment]
Yes and I just copied what you typed directly into kotlinForFRC > simulate > Java Home
 still nothing

**Comment by BrenekH** [comment]
Okay, I've figured out the issue. It seems like PowerShell is doing some funky things while parsing the gradlew command. I'll have to look into the proper fix, but the quick solution is to tell VSCode to use Command Prompt (cmd) as the default shell.

**Comment by BrenekH** [comment]
A fix has been released (version 2023.5.1)
