### ISSUE TITLE
Report Kotlin for usage reporting

### ISSUE THREAD

**Issue by sciencewhiz** [BrenekH/kotlin-for-frc#151]
I noticed that the [FRC usage reporting](https://www.firstinspires.org/robotics/frc/blog/2023-technology-updates-past-present-future-and-beyond) shows a single Kotlin team. I suspect there are more, but Kotlin teams are being reported as Java. Adding the following to the templates will allow them to be reported as Kotlin.
`HAL.report(tResourceType.kResourceType_Language, tInstances.kLanguage_Kotlin);`

**Comment by BrenekH** [comment]
[I've started a PR](https://github.com/BrenekH/kotlin-for-frc/pull/152) to implement this, but I have one question. Should the call to `HAL.report` go before or after WPILib reports Java to the FMS (before `RobotBase.startRobot` or as part of the `Supplier` passed into `RobotBase.startRobot`).

What makes sense in my brain is that the FMS uses the last value passed to it as the final value, but I'm not familiar enough to know for sure.

**Comment by sciencewhiz** [comment]
Yes, it should use the last value

**Comment by BrenekH** [comment]
Alright, this has been released as a part of version 2024.1.1
