### ISSUE TITLE
Doesn't update to GradleRIO 2020.3.2 when using an older version

### ISSUE THREAD

**Issue by BrenekH** [BrenekH/kotlin-for-frc#57]
Kotlin for FRC currently checks only the top-level version tag of the XML it grabs from `https://plugins.gradle.org/m2/edu/wpi/first/GradleRIO/maven-metadata.xml`. 

Instead, KfF should iterate through the `versioning.versions` tags to identify the latest version within the same year.

**Comment by zPaw** [comment]
Fixed by da2a853
